version: "3"

services:

  ew-server:
#    restart: unless-stopped
    healthcheck:
      test: [
        "CMD-SHELL",
        "netstat -tn | grep ${HOST_IP}:${HOST_PORT} || exit 1"
      ]
      interval: 2m
      timeout: 10s
      retries: 3
    build:
      context: .
      dockerfile: Dockerfile
    image: ew-server:latest
    container_name: earthworm-server
    entrypoint: ["python", "/src/client.py"]
    env_file:
      - .env
    environment:
      - HOST_IP=${HOST_IP}
      - HOST_PORT=${HOST_PORT}
    ports:
      - "13340:13340"
