version: "3"

services:

  ew-client:
#    restart: unless-stopped
    healthcheck:
      test: [
        "CMD-SHELL",
        "netstat -tn | grep ${HOST_IP}:${HOST_PORT} || exit 1"
      ]
      interval: 2m
      timeout: 10s
      retries: 3
    build:
      context: .
      dockerfile: Dockerfile
    image: ew-client:latest
    container_name: earthworm-client
    entrypoint: ["python", "/src/client.py"]
    env_file:
      - .env
    environment:
      - HOST_IP=${HOST_IP}
      - HOST_PORT=${HOST_PORT}
    volumes:
      - ./src:/src/
    networks:
      - ew-server-net

networks:
    ew-server-net:
      external: true

